package ventanas;

import departamento.Mantenimiento;
import entidades.Conversion;
import entidades.TipoUnidadMedida;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class conversion extends javax.swing.JFrame {


    Mantenimiento oM;
    DefaultTableModel model;

    public conversion() {
        initComponents();
        setSize(650, 410);
        setResizable(false);//evitar que se mueva sus dimensiones
        setLocationRelativeTo(null);//mantenerlo en el centro
        setTitle("Conversiones");

        ImageIcon conversion_fondo = new ImageIcon("src/images/interfaz_conversiones.jpg");
        Icon icono = new ImageIcon(conversion_fondo.getImage().getScaledInstance(jLabel_conversion.getWidth(), jLabel_conversion.getHeight(), Image.SCALE_DEFAULT));

        jLabel_conversion.setIcon(icono);
        this.repaint();
        oM = new Mantenimiento();
        oM.getTtu().Consultar();
        oM.getTum().Consultar();
        oM.getTco().Consultar();

        model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("De");
        model.addColumn("A");
        model.addColumn("Factor");
        tabla_converisones.setModel(model);

        List<TipoUnidadMedida> ltm = oM.getTtu().Seleccionar("");
        //lleno combo t.u.m.
        for (int i = 0; i < ltm.size(); i++) {
            combo_tu.addItem(ltm.get(i).getNombre());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tm = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        combo_tu = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_converisones = new javax.swing.JTable();
        jLabel_conversion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_tm.setBackground(new java.awt.Color(55, 55, 55));
        jL_tm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_tm.setForeground(new java.awt.Color(0, 0, 0));
        jL_tm.setText("Tipo U.M.");
        getContentPane().add(jL_tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 20));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        getContentPane().add(combo_tu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 300, 30));

        btn_buscar.setBackground(new java.awt.Color(0, 0, 153));
        btn_buscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 80, 30));

        tabla_converisones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_converisones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 510, 160));
        getContentPane().add(jLabel_conversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        oM.getTco().Guardar();
        this.setVisible(false);
        SUPERMERCADO os = new SUPERMERCADO();
        os.setVisible(true);

    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

        Nuevo_conversion ncv = new Nuevo_conversion(this);
        ncv.setVisible(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        int fila = model.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        String tp = (String) combo_tu.getSelectedItem();
        List<Conversion> lcon = oM.getTco().Seleccionar(tp);

        for (int i = 0; i < lcon.size(); i++) {
            
            String[] columns = new String[4];
//            columns[0] = String.valueOf(i + 1);
            columns[0] = lcon.get(i).getCodigo();
            columns[1] = lcon.get(i).getDE();
            columns[2] = lcon.get(i).getA();
            columns[3] = Float.toString(lcon.get(i).getFactor());
            model.addRow(columns);
            
        }


    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        Modificar_conversion oc = new Modificar_conversion(this);
        oc.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
        int row = tabla_converisones.getSelectedRow();
        int fila = tabla_converisones.getRowCount();
        if(fila>0){
            String codigo = (String) model.getValueAt(row, 0); 
            Conversion oc = new Conversion(codigo);
            oM.getTco().Eliminar(oc);
            model.removeRow(row); //elimino de la fila
            oM.getTco().Guardar();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un elemento.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> combo_tu;
    private javax.swing.JLabel jL_tm;
    private javax.swing.JLabel jLabel_conversion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_converisones;
    // End of variables declaration//GEN-END:variables
}
