/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import departamento.Mantenimiento;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import entidades.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROBERT
 */
public class producto extends javax.swing.JFrame {

    DefaultTableModel model;
    Mantenimiento oM;

    public producto() {
        initComponents();
        setSize(650, 380);
        setResizable(false);//evitar que se mueva sus dimensiones
        setLocationRelativeTo(null);//mantenerlo en el centro
        setTitle("Ventana Producto");

        ImageIcon producto_fondo = new ImageIcon("src/images/interfaz_producto.jpg");
        Icon icono = new ImageIcon(producto_fondo.getImage().getScaledInstance(jLabel_producto.getWidth(), jLabel_producto.getHeight(), Image.SCALE_DEFAULT));

        jLabel_producto.setIcon(icono);
        this.repaint();

        model = new DefaultTableModel();
//        model.addColumn("N°");
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("U.medida");
        model.addColumn("P.unitario");

        tabla_producto.setModel(model);

        oM = new Mantenimiento();
        oM.getTpr().Consultar();
        oM.getTum().Consultar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nombre = new javax.swing.JLabel();
        txt_barra = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_producto = new javax.swing.JTable();
        jLabel_producto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nombre.setBackground(new java.awt.Color(55, 55, 55));
        jLabel_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setText("Nombre");
        getContentPane().add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 20));

        txt_barra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 300, 30));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 80, 30));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        tabla_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_producto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 550, 160));
        getContentPane().add(jLabel_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_barraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barraActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        //limpio tabla
        int row = model.getRowCount();
        
        for(int i = row-1;i>=0;i--){
            model.removeRow(i);
        }
        
        String patron;
        patron = txt_barra.getText();
        List<Producto> lpro = oM.getTpr().Seleccionar(patron);

        for (int i = 0; i < lpro.size(); i++) {
            String[] columns = new String[4];
//            columns[0] = Integer.toString(i+1);
            columns[0] = lpro.get(i).getCodigo();
            columns[1] = lpro.get(i).getNombre();
            columns[2] = lpro.get(i).getUnidadMedida();
            columns[3] = Float.toString(lpro.get(i).getPrecioUnitario());

            model.addRow(columns);

        }

//        JOptionPane.showMessageDialog(null, patron, "Mensaje de bienvenida", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        Nuevo_Producto pnv = new Nuevo_Producto(this);
        pnv.setVisible(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        oM.getTpr().Guardar();
                
        this.dispose();
        SUPERMERCADO os = new SUPERMERCADO();
        os.setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
        int row = tabla_producto.getSelectedRow();
        int fila = tabla_producto.getRowCount();
        if(fila>0){
            String codigo = (String) model.getValueAt(row, 0); //model = tabla_producto
            Producto op = new Producto(codigo);
            oM.getTpr().Eliminar(op);
            model.removeRow(row); //elimino de la fila
            this.oM.getTpr().Guardar();
        }else{
            JOptionPane.showMessageDialog(null, "No hay producto seleccionados", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        
        Modificar_Producto om = new Modificar_Producto(this);
        om.setVisible(true);
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new producto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_producto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_producto;
    private javax.swing.JTextField txt_barra;
    // End of variables declaration//GEN-END:variables
}
