/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import departamento.Mantenimiento;
import entidades.UnidadMedida;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROBERT
 */
public class unidadmedida extends javax.swing.JFrame {

    Mantenimiento oM;
    DefaultTableModel model;

    public unidadmedida() {
        initComponents();
        setSize(660, 410);
        setResizable(false);//evitar que se mueva sus dimensiones
        setLocationRelativeTo(null);//mantenerlo en el centro
        setTitle("Ventana Unidad Medida");



        model = new DefaultTableModel();
//        model.addColumn("N°");
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        tabla_um.setModel(model);

        oM = new Mantenimiento();
        oM.getTtu().Consultar();
        oM.getTum().Consultar();

        List<entidades.TipoUnidadMedida> ltu = oM.getTtu().Seleccionar("");
        //listo el combo de tu
        for (int i = 0; i < ltu.size(); i++) {
            combo_tpu.addItem(ltu.get(i).getNombre());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_tu = new javax.swing.JLabel();
        jL_nombre = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_um = new javax.swing.JTable();
        combo_tpu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_nombre.setBackground(new java.awt.Color(55, 55, 55));
        jL_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jL_nombre.setText("Nombre");
        getContentPane().add(jL_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 20));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 80, 30));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 80, 30));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 30));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 80, 30));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 80, 30));

        tabla_um.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_um);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 570, 160));

        getContentPane().add(combo_tpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 270, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        //limpiamos tabla
        int fila = model.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        String tu;
        tu = (String) combo_tpu.getSelectedItem();
        List<entidades.UnidadMedida> lum = oM.getTum().Seleccionar(tu);
        
        for (int i = 0; i < lum.size(); i++) {

            String[] columns = new String[2];
//            columns[0] = String.valueOf(i + 1); 
            columns[0] = lum.get(i).getCodigo();
            columns[1] = lum.get(i).getUnidadMedida();
            model.addRow(columns);
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed

        Nuevo_UM nv = new Nuevo_UM(this);
        nv.setVisible(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.oM.getTum().Guardar();
        this.setVisible(false);
        SUPERMERCADO os = new SUPERMERCADO();
        os.setVisible(true);

    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        
        Modificar_UM um = new Modificar_UM(this);
        um.setVisible(true);
        
                
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
         UnidadMedida um = new UnidadMedida();
        int row = this.tabla_um.getSelectedRow(); //selecciono la fila que deseo eliminar

        if (row >= 0) {

 
            String codElimniar = (String) tabla_um.getValueAt(row, 0); //en ste caso es row->fila  y  1->la columna codigo
            um.setCodigo(codElimniar);
            this.oM.getTum().Eliminar(um);
            JOptionPane.showMessageDialog(this, "sizeum: "+ oM.getTum().size());
            model.removeRow(row); //elimino de la fila
            
            

        } else {
            JOptionPane.showMessageDialog(null, "No hay producto seleccionados", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(unidadmedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(unidadmedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(unidadmedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(unidadmedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new unidadmedida().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> combo_tpu;
    private javax.swing.JLabel combo_tu;
    private javax.swing.JLabel jL_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_um;
    // End of variables declaration//GEN-END:variables
}
